CREATE USER lenic_migrator WITH LOGIN;

GRANT ALL PRIVILEGES ON DATABASE "lenicDB" TO lenic_migrator;
ALTER SCHEMA public OWNER TO lenic_migrator;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO lenic_migrator;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO lenic_migrator;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON TABLES TO lenic_migrator;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT ALL PRIVILEGES ON SEQUENCES TO lenic_migrator;
